'use strict';

// client => server actions
exports.CREATE_GROUP = 'CREATE_GROUP';
exports.JOIN_GROUP = 'JOIN_GROUP';
exports.CHARACTER_CHOSEN = 'CHARACTER_CHOSEN';
exports.START_ADVENTURE = 'START_ADVENTURE';
exports.SUBMIT_ACTION = 'SUBMIT_ACTION';
exports.CHARACTER_NEGATE = 'CHARACTER_NEGATE';

// server => client actions
exports.CLIENT_CONNECTED = 'CLIENT_CONNECTED';
exports.CHARACTER_SELECT_STATE = 'CHARACTER_SELECT_STATE';
exports.ADVENTURE_STATE = 'ADVENTURE_STATE';
