'use strict';

exports.CREATE_GROUP = 'CREATE_GROUP';
exports.JOIN_GROUP = 'JOIN_GROUP';
exports.CHARACTER_CHOSEN = 'CHARACTER_CHOSEN';
exports.START_ADVENTURE = 'START_ADVENTURE';
exports.SUBMIT_ACTION = 'SUBMIT_ACTION';
